<?php
// Script to merge and consolidate Department/Office names in plantilla_records

require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use Illuminate\Support\Facades\DB;

$consolidations = [
    // Hospitals
    'BUKIDNON PROVINCIAL HOSPITAL - KIBAWE' => ['BPH-KIBAWE', 'BUKIDNON PROVINCIAL HOSPITAL - KIBAWE'],
    'BUKIDNON PROVINCIAL HOSPITAL - MARAMAG' => ['BPH-MARAMAG', 'BUKIDNON PROVINCIAL HOSPITAL OF MARAMAG', 'BUKIDNON PROVINCIAL HOSPITAL - MARAMAG'],
    'BUKIDNON PROVINCIAL HOSPITAL - MANOLO FORTICH' => ['BPH-MANOLO FORTICH', 'BUKIDNON PROVINCIAL HOSPITAL OF MANOLO FORTICH', 'BUKIDNON PROVINCIAL HOSPITAL - MANOLO FORTICH'],
    'BUKIDNON PROVINCIAL HOSPITAL - KALILANGAN' => ['BPH-KALILANGAN', 'BUKIDNON PROVINCIAL HOSPITAL-KALILANGAN', 'BUKIDNON PROVINCIAL HOSPITAL - KALILANGAN'],
    'BUKIDNON PROVINCIAL HOSPITAL - SAN FERNANDO' => ['BPH-SAN FERNANDO', 'BUKIDNON PROVINCIAL HOSPITAL - SAN FERNANDO'],
    'BUKIDNON PROVINCIAL HOSPITAL - TALAKAG' => ['BPH-TALAKAG', 'BUKIDNON PROVINCIAL HOSPITAL - TALAKAG'],
    'BUKIDNON PROVINCIAL HOSPITAL - MALITBOG' => ['BPH-MALITBOG', 'BUKIDNON PROVINCIAL HOSPITAL - MALITBOG'],
    'BUKIDNON PROVINCIAL MEDICAL CENTER' => ['BUKIDNON PROVINCIAL MEDICAL CENTER - Malaybalay City', 'BUKIDNON PROVINCIAL MEDICAL CENTER - MALAYBALAY', 'BUKIDNON PROVINCIAL MEDICAL CENTER'],
    
    // Environment
    'BUKIDNON ENVIRONMENT AND NATURAL RESOURCES OFFICE' => ['BUKIDNON ENVIRONMENT & NATURAL RESOURCES OFFICE', 'BUKIDNON ENVIRONMENT AND NATURAL RESOURCES OFFICE'],

    // Provincial Governor's Office
    'PROVINCIAL GOVERNOR\'S OFFICE - MANAGEMENT AND STAFF' => ['PGO-MANAGEMENT', 'PROVINCIAL GOVERNOR\'S OFFICE-MANAGEMENT AND STAFF', 'PROVINCIAL GOVERNOR\'S OFFICE - MANAGEMENT AND STAFF'],
    'PROVINCIAL GOVERNOR\'S OFFICE - CIVIL SECURITY UNIT' => ['PGO-CIVIL SECURITY UNIT', 'PROVINCIAL GOVERNOR\'S OFFICE - CIVIL SECURITY UNIT'],
    'PROVINCIAL GOVERNOR\'S OFFICE - PROVINCIAL DETENTION AND REHABILITATION CENTER' => ['PGO-PROVINCIAL DETENTION & REHABILATATION CENTER', 'PROVINCIAL GOVERNOR\'S OFFICE - PROVINCIAL DETENTION AND REHABILIITATION CENTER', 'PROVINCIAL GOVERNOR\'S OFFICE - PROVINCIAL DETENTION AND REHABILITATION CENTER'],
    'PROVINCIAL GOVERNOR\'S OFFICE - PROVINCIAL INFORMATION AND COMMUNICATION TECHNOLOGY DIVISION' => ['PGO-PROVINCIAL INFORMATION & COMMUNICATION TECHNOLOGY DIVISION', 'PROVINCIAL GOVERNOR\'S OFFICE - PROVINCIAL INFORMATION AND COMMUNICATION TECHNOLOGY DIVISION'],
    'PROVINCIAL GOVERNOR\'S OFFICE - INDIGENOUS AFFAIRS' => ['PGO-INDIGENOUS AFFAIRS DIVISION', 'PROVINCIAL GOVERNOR\'S OFFICE - INDIGENOUS AFFAIRS'],
    'PROVINCIAL GOVERNOR\'S OFFICE - RADIO COMMUNICATION' => ['PGO-RADIO COMMUNICATIONS', 'PROVINCIAL GOVERNOR\'S OFFICE - RADIO COMMUNICATION'],
    'PROVINCIAL GOVERNOR\'S OFFICE - POPULATION DEVELOPMENT' => ['PGO-POPULATION DEVELOPMENT', 'PROVINCIAL GOVERNOR\'S OFFICE - POPULATION DEVELOPMENT'],
    'PROVINCIAL GOVERNOR\'S OFFICE - PUBLIC AFFAIRS, INFORMATION AND ASSISTANCE' => ['PGO-PUBLIC ASSISTANCE AND INFORMATION AFFAIRS', 'PROVINCIAL GOVERNOR\'S OFFICE - PUBLIC AFFAIRS, INFORMATION AND ASSISTANCE'],
    'PROVINCIAL GOVERNOR\'S OFFICE - BUKIDNON PROVINCIAL ZOO' => ['PGO- BUKIDNON PROVINCIAL ZOO', 'PGO-ZOO', 'PROVINCIAL GOVERNOR\'S OFFICE - BUKIDNON PROVINCIAL ZOO'],
    'PROVINCIAL GOVERNOR\'S OFFICE - REAL ESTATE AND HOUSING DEVELOPMENT DIVISION' => ['PGO-RESETTLEMENT AND HOUSING DEVELOPMENT DIVISION', 'PROVINCIAL GOVERNOR\'S OFFICE - REAL ESTATE & HOUSING DEVELOPMENT DIVISION', 'PROVINCIAL GOVERNOR\'S OFFICE - REAL ESTATE AND HOUSING DEVELOPMENT DIVISION'],

    // Social Welfare
    'PROVINCIAL SOCIAL WELFARE AND DEVELOPMENT OFFICE' => ['PROVINCIAL SOCIAL WELFARE & DEVELOPMENT OFFICE', 'PROVINCIAL SOCIAL WELFARE AND DEVELOPMENT OFFICE'],

    // Provincial Health Office
    'PROVINCIAL HEALTH OFFICE - TECHNICAL' => ['PHO-TECHNICAL', 'PROVINCIAL HEALTH OFFICE - TECHNICAL'],

    // Economic Enterprise
    'PROVINCIAL ECONOMIC ENTERPRISE DEVELOPMENT AND MANAGEMENT OFFICE' => ['PROVINCIAL ECONOMIC ENTERPRISE DEVELOPMENT & MANAGEMENT OFFICE', 'PROVINCIAL ECONOMIC ENTERPRISE DEVELOPMENT AND MANAGEMENT OFFICE'],

    // Agriculture/Biosystems
    'PROVINCIAL AGRICULTURAL AND BIOSYSTEMS ENGINEER OFFICE' => ['PROVINCIAL AGRICULTURAL AND BIOSYSTEMS ENGINEERING', 'PROVINCIAL AGRICULTURAL AND BIOSYSTEMS ENGINEER OFFICE'],

    // Accountant
    'PROVINCIAL ACCOUNTANT\'S OFFICE' => ['PROVINCAL ACCOUNTANT\'S OFFICE', 'PROVINCIAL ACCOUNTANT\'S OFFICE'],

    // Disability
    'PROVINCIAL PERSONS WITH DISABILITY AFFAIRS OFFICE' => ['PROVINCIAL PERSONS WITH DISABILITIES AFFAIRS OFFICE', 'PROVINCIAL PERSONS WITH DISABILITY AFFAIRS OFFICE'],

    // Sangguniang Panlalawigan
    'SANGGUNIANG PANLALAWIGAN OFFICE' => ['SANGGUNIANG PANLALAWIGAN', 'SANGGUNIANG PANLALAWIGAN OFFICE'],
    'SP-ALBARECE, JR.' => ['SP-ALBARECE', 'SP-ALBARECE, JR.'],
    'SP-MARLON DINLAYAN' => ['SP-DINLAYAN M.', 'SP-MARLON DINLAYAN'],
    'SP-BOBBY JAY DINLAYAN' => ['SP-DINLAYAN B.', 'SP-BOBBY JAY DINLAYAN'],
    'SP-EVANGELISTA, JR.' => ['SP-EVANGELISTA', 'SP-EVANGELISTA, JR.'],

    // Vice Governor
    'PROVINCIAL VICE GOVERNOR\'S OFFICE' => ['PROVINCIAL VICE GOVERNOR OFFICE', 'PROVINCIAL VICE GOVERNOR\'S OFFICE'],

    // DILG
    'DEPARTMENT OF INTERIOR AND LOCAL GOVERNMENT' => ['DEPARTMENT OF INTERIOR & LOCAL GOVERNMENT', 'DEPARTMENT OF INTERIOR AND LOCAL GOVERNMENT']
];

$totalUpdated = 0;

foreach ($consolidations as $targetName => $sourceNames) {
    // Filter out target name from source names to avoid self-updates
    $sourceNames = array_filter($sourceNames, function($name) use ($targetName) {
        return $name !== $targetName;
    });

    if (empty($sourceNames)) {
        continue;
    }

    $updated = DB::table('plantilla_records')
        ->whereIn('office_department', $sourceNames)
        ->update(['office_department' => $targetName]);
    
    if ($updated > 0) {
        echo "Merged " . implode(", ", $sourceNames) . " -> {$targetName} ({$updated} records)\n";
        $totalUpdated += $updated;
    }
}

// Update organizational_units table as well if it exists
if (Schema::hasTable('organizational_units')) {
    echo "\nSyncing organizational_units...\n";
    $distinctOffices = DB::table('plantilla_records')->distinct()->pluck('office_department');
    
    // Insert missing
    foreach ($distinctOffices as $office) {
        if ($office && !DB::table('organizational_units')->where('name', $office)->exists()) {
            DB::table('organizational_units')->insert([
                'name' => $office,
                'code' => strtoupper(substr(preg_replace('/[^A-Za-z0-9]/', '', $office), 0, 5)) . '_' . rand(1000, 9999),
                'created_at' => now(), 
                'updated_at' => now()
            ]);
            echo "Added {$office} to organizational_units\n";
        }
    }
    
    // Delete unused
    $unused = DB::table('organizational_units')->whereNotIn('name', $distinctOffices)->get();
    foreach ($unused as $u) {
        DB::table('organizational_units')->where('id', $u->id)->delete();
        echo "Removed unused {$u->name} from organizational_units\n";
    }
}

echo "\nDone! Total records updated: {$totalUpdated}\n";
