<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>PWD Personnel Report</title>
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #1f2937; margin: 20px; }
    h1   { font-size: 15px; font-weight: 700; margin: 0 0 4px; }
    .sub { font-size: 10px; color: #6b7280; margin-bottom: 14px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    thead th {
        background: #0d9488; color: #fff; text-align: left;
        padding: 7px 8px; font-size: 9px; text-transform: uppercase; letter-spacing: .4px;
    }
    tbody td { padding: 6px 8px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }
    tbody tr:nth-child(even) td { background: #f9fafb; }
    .name { font-weight: 700; text-transform: uppercase; }
    .item { font-family: monospace; color: #6b7280; font-size: 9px; }
    .footer { margin-top: 16px; font-size: 8px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 6px; }
</style>
</head>
<body>
<h1>PWD Personnel Report</h1>
<div class="sub">Persons with Disabilities (PWD) in Filled Plantilla Positions &nbsp;|&nbsp; As of {{ now()->format('F d, Y') }} &nbsp;|&nbsp; {{ $pwdRecords->count() }} record(s)</div>

<table>
    <thead>
        <tr>
            <th style="width:25px;">#</th>
            <th>Name</th>
            <th style="width:130px;">Type of Disability</th>
            <th>Office / Unit</th>
            <th>Position Title</th>
            <th style="width:55px;">App't Status</th>
            <th style="width:30px;">SG</th>
        </tr>
    </thead>
    <tbody>
        @forelse($pwdRecords as $i => $r)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td>
                <span class="name">{{ $r->last_name }}, {{ $r->first_name }} {{ $r->middle_name ? strtoupper(substr($r->middle_name,0,1)).'.' : '' }}</span><br>
                <span class="item">{{ $r->item }}</span>
            </td>
            <td>{{ $r->type_of_disability ?? 'Unspecified' }}</td>
            <td>{{ $r->organizational_unit }}</td>
            <td>{{ $r->position_title }}</td>
            <td>{{ strtoupper($r->employment_status ?? '—') }}</td>
            <td>{{ $r->salary_grade }}</td>
        </tr>
        @empty
        <tr><td colspan="7" style="text-align:center; color:#9ca3af; padding:16px;">No PWD personnel found.</td></tr>
        @endforelse
    </tbody>
</table>

<div class="footer">Generated by HDMS- Human Resource Data Management System &nbsp;·&nbsp; {{ now()->format('Y-m-d H:i') }}</div>
</body>
</html>
