<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Vacant Funded/Unfunded Positions</title>
<style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; margin: 20px; }
    h1   { font-size: 16px; font-weight: 700; margin: 0 0 4px; }
    .sub { font-size: 11px; color: #6b7280; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    thead th {
        background: {{ $type === 'funded' ? '#1d4ed8' : '#4b5563' }};
        color: #fff; text-align: left;
        padding: 7px 10px; font-size: 10px; text-transform: uppercase; letter-spacing: .5px;
    }
    tbody td { padding: 7px 10px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }
    tbody tr:nth-child(even) td { background: #f9fafb; }
    .item { font-family: monospace; color: #6b7280; }
    .footer { margin-top: 20px; font-size: 9px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 8px; }
</style>
</head>
<body>
<h1>{{ $title }}</h1>
<div class="sub">As of {{ now()->format('F d, Y') }} &nbsp;|&nbsp; {{ $records->count() }} position(s)</div>

<table>
    <thead>
        <tr>
            <th style="width:30px;">#</th>
            <th style="width:90px;">Item No.</th>
            <th>Position Title</th>
            <th>Office / Unit</th>
            <th style="width:40px;">SG</th>
            <th style="width:40px;">Step</th>
            <th style="width:110px;">Ann. Salary</th>
            <th style="width:70px;">Status</th>
        </tr>
    </thead>
    <tbody>
        @forelse($records as $i => $r)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td class="item_no_new">{{ $r->item_no_new }}</td>
            <td>{{ $r->position_title }}</td>
            <td>{{ $r->office_department }}</td>
            <td>{{ $r->salary_grade }}</td>
            <td>{{ $r->step }}</td>
            <td>{{ number_format($r->authorized_annual_salary ?? 0, 2) }}</td>
            <td>{{ $r->abolished ? 'Abolished' : ($r->dissolved ? 'Dissolved' : 'Vacant') }}</td>
        </tr>
        @empty
        <tr><td colspan="8" style="text-align:center; color:#9ca3af; padding:20px;">No records found.</td></tr>
        @endforelse
    </tbody>
</table>

<div class="footer">Generated by HDMS- Human Resource Data Management System &nbsp;·&nbsp; {{ now()->format('Y-m-d H:i') }}</div>
</body>
</html>
