<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Vacant Funded – {{ $position }}</title>
<style>
    body  { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; margin: 20px; }
    .gov  { font-size: 9px; color: #6b7280; text-transform: uppercase; letter-spacing: .6px; margin-bottom: 2px; }
    h1    { font-size: 16px; font-weight: 700; margin: 0 0 2px; color: #1d4ed8; }
    .pos  { font-size: 13px; font-weight: 700; color: #0f172a; margin-bottom: 2px; }
    .sub  { font-size: 10px; color: #6b7280; margin-bottom: 14px; }
    hr    { border: none; border-top: 2px solid #1d4ed8; margin: 10px 0 14px; }
    table { width: 100%; border-collapse: collapse; margin-top: 4px; }
    thead th {
        background: #1d4ed8; color: #fff;
        text-align: left; padding: 7px 10px;
        font-size: 9.5px; text-transform: uppercase; letter-spacing: .5px;
    }
    tbody td { padding: 7px 10px; border-bottom: 1px solid #f3f4f6; vertical-align: top; font-size: 10.5px; }
    tbody tr:nth-child(even) td { background: #eff6ff; }
    .item { font-family: monospace; color: #6b7280; }
    .money { text-align: right; font-family: monospace; }
    .footer { margin-top: 20px; font-size: 8.5px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 8px; display: flex; justify-content: space-between; }
    .summary { margin-top: 14px; background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 6px; padding: 8px 12px; font-size: 10px; }
    .summary strong { color: #1d4ed8; }
</style>
</head>
<body>

<div class="gov">Republic of the Philippines — Civil Service Commission</div>
<h1>Vacant Funded Positions</h1>
<div class="pos">{{ $position }}</div>
<div class="sub">As of {{ now()->format('F d, Y') }} &nbsp;|&nbsp; {{ $records->count() }} slot(s) open</div>
<hr>

<table>
    <thead>
        <tr>
            <th style="width:26px;">#</th>
            <th style="width:88px;">Item No.</th>
            <th style="width:36px;">SG</th>
            <th style="width:36px;">Step</th>
            <th>OFFICE</th>
            <th style="width:110px;">Auth. Annual Salary</th>
            <th style="width:72px;">Area Code</th>
            <th style="width:60px;">Level</th>
        </tr>
    </thead>
    <tbody>
        @forelse($records as $i => $r)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td class="item_no_new">{{ $r->item_no_new }}</td>
            <td style="text-align:center; font-weight:700;">{{ $r->salary_grade }}</td>
            <td style="text-align:center;">{{ $r->step }}</td>
            <td>{{ $r->office_department }}</td>
            <td class="money">₱{{ number_format($r->authorized_annual_salary ?? 0, 2) }}</td>
            <td>{{ $r->area_code }}</td>
            <td>{{ $r->level }}</td>
        </tr>
        @empty
        <tr><td colspan="8" style="text-align:center; color:#9ca3af; padding:20px;">No records found.</td></tr>
        @endforelse
    </tbody>
</table>

@if($records->isNotEmpty())
<div class="summary">
    <strong>Total Slots:</strong> {{ $records->count() }}
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <strong>Total Auth. Annual Salary:</strong>
    ₱{{ number_format($records->sum('authorized_annual_salary'), 2) }}
</div>
@endif

<div class="footer">
    <span>Generated by HDMS- Human Resource Data Management System</span>
    <span>{{ now()->format('Y-m-d H:i') }}</span>
</div>
</body>
</html>
