<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>HRMPSB Deliberation Agenda</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h3 { margin: 0; font-size: 16px; font-weight: bold; }
        .header p { margin: 5px 0; font-size: 12px; }
        .section-title { background: #333; color: #fff; padding: 5px; font-weight: bold; margin-top: 20px; margin-bottom: 10px; font-size: 13px; }
        .notes-content { white-space: pre-wrap; font-size: 12px; margin-bottom: 20px; line-height: 1.5; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ccc; padding: 6px; text-align: left; }
        th { background: #f4f4f4; font-weight: bold; }
        .office-row { background: #e0e0e0; font-weight: bold; }
        .vacancy-row { background: #f0f0f0; font-style: italic; }
        .badge-jo { color: #d97706; font-weight: bold; }
        .badge-ex { color: #16a34a; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 10px; text-align: center; color: #777; }
    </style>
</head>
<body>

    <div class="header">
        <h3>PROVINCIAL GOVERNMENT OF BUKIDNON</h3>
        <p>Provincial Human Resource Management Office</p>
        <p><strong>{{ $agenda->title }}</strong></p>
        <p>Generated on {{ \Carbon\Carbon::parse($agenda->created_at)->format('F d, Y h:i A') }}</p>
    </div>

    @if($agenda->part_1_notes)
    <div class="section-title">Part I: Preliminary Notes</div>
    <div class="notes-content">{{ $agenda->part_1_notes }}</div>
    @endif

    <div class="section-title">Part II: Deliberation Matrix</div>
    <table>
        <thead>
            <tr>
                <th style="width: 40%">Applicant Name</th>
                <th style="width: 20%">Category Tag</th>
                <th style="width: 40%">Board Resolution / Action Taken</th>
            </tr>
        </thead>
        <tbody>
            @foreach($agenda->matrix_data as $office => $positions)
                <tr class="office-row">
                    <td colspan="3">Office: {{ $office }}</td>
                </tr>
                @foreach($positions as $pos => $details)
                    @php
                        $isNewFormat = isset($details['applicants']);
                        $applicants = $isNewFormat ? $details['applicants'] : $details;
                    @endphp
                    <tr class="vacancy-row">
                        <td colspan="3">
                            Vacancy: {{ $pos }}
                            @if($isNewFormat)
                                <span style="font-size:10px; color:#555; margin-left: 10px;">
                                    (Item No: {{ $details['item_no'] ?? 'N/A' }} | SG-{{ $details['sg'] ?? 'N/A' }} | ₱ {{ number_format((float)($details['rate'] ?? 0), 2) }})
                                </span>
                            @endif
                        </td>
                    </tr>
                    @foreach($applicants as $app)
                        <tr>
                            <td style="padding-left: 20px;">{{ $app['name'] }}</td>
                            <td>
                                @if($app['tag'] === 'Job Order')
                                    <span class="badge-jo">Job Order</span>
                                @elseif($app['tag'] === 'Exempted')
                                    <span class="badge-ex">Exempted</span>
                                @else
                                    <span>External</span>
                                @endif
                            </td>
                            <td>{{ $app['resolution'] ?? '' }}</td>
                        </tr>
                    @endforeach
                @endforeach
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by the HRDMS System &bull; HRMPSB Deliberation Form
    </div>

</body>
</html>
