<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Candidate Evaluation Report - Level 2</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h3 { margin: 0; font-size: 14px; font-weight: bold; }
        .header p { margin: 2px 0; font-size: 11px; }
        .title { text-align: center; font-weight: bold; font-size: 13px; margin: 15px 0; text-decoration: underline; color: #1e3a8a; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; }
        th, td { border: 1px solid #333; padding: 6px; }
        th { background: #e0e7ff; text-align: left; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .fw-bold { font-weight: bold; }
        .bg-light { background-color: #f8fafc; }
    </style>
</head>
<body>
    <div class="header">
        <h3>PROVINCIAL GOVERNMENT OF BUKIDNON</h3>
        <p>Provincial Human Resource Management Office</p>
    </div>

    <div class="title">CANDIDATE EVALUATION REPORT (CER) - LEVEL 2 (SUPERVISORY)</div>

    <table>
        <tr>
            <th style="width: 20%">Applicant Name:</th>
            <td style="width: 30%" class="fw-bold">{{ $applicant->last_name }}, {{ $applicant->first_name }}</td>
            <th style="width: 20%">Date Evaluated:</th>
            <td style="width: 30%">{{ $twgSubmission ? \Carbon\Carbon::parse($twgSubmission->submitted_at)->format('M d, Y') : 'N/A' }}</td>
        </tr>
        <tr>
            <th>Position Applied:</th>
            <td>{{ $applicant->position_applied }}</td>
            <th>Item Number:</th>
            <td>{{ $applicant->item_no ?? 'N/A' }}</td>
        </tr>
        <tr>
            <th>Office / Department:</th>
            <td>{{ $applicant->office ?? 'N/A' }}</td>
            <th>Salary Grade:</th>
            <td>{{ $sg }}</td>
        </tr>
    </table>

    <h4 style="margin-bottom: 5px;">I. Supervisory & TWG Assessment</h4>
    <table>
        <thead>
            <tr>
                <th>Criterion</th>
                <th class="text-center" style="width: 15%">Max Points</th>
                <th class="text-center" style="width: 15%">Assessor Score</th>
            </tr>
        </thead>
        <tbody>
            @foreach($twgScores as $score)
                <tr>
                    <td>{{ $score->criterion->criterion_name }}</td>
                    <td class="text-center">{{ number_format($score->criterion->point_value, 2) }}</td>
                    <td class="text-center">{{ number_format($score->assessor_value, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="fw-bold bg-light">
                <td class="text-right">Total Score:</td>
                <td class="text-center">{{ number_format($twgScores->sum(fn($s) => $s->criterion->point_value), 2) }}</td>
                <td class="text-center">{{ $twgSubmission ? number_format($twgSubmission->total_assessor, 2) : '0.00' }}</td>
            </tr>
        </tfoot>
    </table>

    <h4 style="margin-bottom: 5px;">II. HRMPSB Interview & Competency Assessment</h4>
    <table>
        <tr>
            <th style="width: 70%">Average Panel Score (Supervisory/Managerial Scale)</th>
            <td class="text-center fw-bold" style="width: 30%; font-size: 14px;">
                @if($hrmpsbEvaluations->count() > 0)
                    {{ number_format($hrmpsbEvaluations->avg('total_score'), 2) }}
                @else
                    N/A
                @endif
            </td>
        </tr>
    </table>

    <h4 style="margin-bottom: 5px;">III. Executive Recommendation</h4>
    <table>
        <tr>
            <th style="width: 25%">Final Classification:</th>
            <td style="width: 25%" class="fw-bold">{{ $twgSubmission ? $twgSubmission->adjectival_classification : 'N/A' }}</td>
            <th style="width: 25%">Recommendation:</th>
            <td style="width: 25%" class="fw-bold">{{ $twgSubmission ? $twgSubmission->recommendation : 'Pending' }}</td>
        </tr>
        <tr>
            <td colspan="4" style="height: 80px; vertical-align: top;">
                <strong>Justification & Remarks:</strong><br>
                {{ $twgSubmission ? $twgSubmission->overall_notes : '' }}
            </td>
        </tr>
    </table>

    <div style="margin-top: 40px; text-align: right; border-top: 1px solid #ccc; padding-top: 5px;">
        <p>Prepared by the Technical Working Group<br>Generated by HRDMS on {{ now()->format('M d, Y h:i A') }}</p>
    </div>
</body>
</html>
